# Generated by Django 3.2.7 on 2021-09-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210916_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='test.jpeg', null=True, upload_to='event/'),
        ),
    ]
