# Generated by Django 3.2.7 on 2021-09-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='done_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
            preserve_default=False,
        ),
    ]
